import React from 'react';

export const MapSection = () => {
    // Exact embed URL provided by the user
    // This is the most reliable way as it uses the 'pb' parameter generated by Google Maps itself.
    const mapUrl = `https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d29197.435785722846!2d89.05402191083985!3d23.829994300000003!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x8a77a1c017f8757b%3A0xae943c063538c2b5!2sAS%20Marketing%20Business!5e0!3m2!1sen!2sbd!4v1766386068586!5m2!1sen!2sbd`;

    return (
        <section className="py-20 relative bg-slate-50/50">
            <div className="container mx-auto px-4 md:px-6">
                <div className="text-center mb-12">
                    <h2 className="text-3xl md:text-4xl font-bold text-heading mb-4">
                        আমাদের লোকেশন
                    </h2>
                    <div className="w-20 h-1 bg-brand-neon mx-auto rounded-full" />
                </div>

                <div className="max-w-5xl mx-auto bg-white p-3 md:p-4 rounded-3xl shadow-xl border border-slate-100 relative group overflow-hidden">
                    {/* Decorative elements */}
                    <div className="absolute top-0 left-0 w-full h-1 bg-gradient-to-r from-brand-neon via-purple-500 to-pink-500 z-10" />

                    <div className="relative w-full h-[300px] md:h-[450px] rounded-2xl overflow-hidden shadow-inner bg-slate-100">
                        <iframe
                            width="100%"
                            height="100%"
                            src={mapUrl}
                            title="Google Map - AS Marketing Business"
                            style={{ border: 0 }}
                            allowFullScreen
                            loading="lazy"
                            referrerPolicy="no-referrer-when-downgrade"
                            className="w-full h-full"
                        ></iframe>
                    </div>
                </div>
            </div>
        </section>
    );
};
